'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion: 4.0.30319.42000
'
'     Änderungen an dieser Datei können zu fehlerhaftem Verhalten führen und gehen
'     verloren, wenn der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    ' HINWEIS: Diese Datei wird automatisch generiert; nicht direkt bearbeiten. Um Änderungen vorzunehmen,
    ' oder wenn in dieser Datei Buildfehler auftreten, öffnen Sie den Projekt-Designer
    ' (über Projekteigenschaften oder durch Doppelklick auf den Knoten "Mein Projekt" im
    ' Projektmappen-Explorer) und nehmen Sie die Änderungen auf der Registerkarte "Anwendung" vor.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.AniGifControlTest.FormMain
        End Sub

    End Class

End Namespace
