'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SchlumpfSoft.Controls.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AniGifControl_AniGif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AniGifControl_AniGif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AniGifControl_Standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AniGifControl_Standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ColorProgressBarControl_ColorProgressBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorProgressBarControl_ColorProgressBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DriveWatcherControl_DriveWatcher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DriveWatcherControl_DriveWatcher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_Computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_Computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveCDRom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveCDRom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveDisk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveDisk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveFixed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveFixed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveNetwork() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveNetwork", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveNoRoot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveNoRoot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveRamDisk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveRamDisk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveRemovable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveRemovable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveSystem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveSystem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_DriveUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_DriveUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_ExplorerTreeView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_ExplorerTreeView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_FolderDesktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_FolderDesktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_FolderDocuments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_FolderDocuments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_FolderDownloads() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_FolderDownloads", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_FolderMusic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_FolderMusic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_FolderPictures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_FolderPictures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExplorerTreeViewControl_FolderVideos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplorerTreeViewControl_FolderVideos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExtendedRTFControl_ExtendedRTF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtendedRTFControl_ExtendedRTF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FileListControl_FileList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileListControl_FileList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageComboBoxControl_ImageComboBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageComboBoxControl_ImageComboBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniFileControl_CommentEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniFileControl_CommentEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniFileControl_ContentView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniFileControl_ContentView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniFileControl_EntryValueEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniFileControl_EntryValueEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniFileControl_IniFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniFileControl_IniFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniFileControl_ListEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniFileControl_ListEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotifyFormControl_CriticalError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyFormControl_CriticalError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotifyFormControl_Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyFormControl_Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotifyFormControl_NotifyForm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyFormControl_NotifyForm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotifyFormControl_Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyFormControl_Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotifyFormControl_Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyFormControl_Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PasswordControl_noshow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordControl_noshow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PasswordControl_noshowgray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordControl_noshowgray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PasswordControl_Password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordControl_Password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PasswordControl_show() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordControl_show", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PasswordControl_showgray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordControl_showgray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SevenSegmentControl_MultiDigit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenSegmentControl_MultiDigit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SevenSegmentControl_SingleDigit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenSegmentControl_SingleDigit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ShapeControl_Shape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShapeControl_Shape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransparentLabelControl_TransparentLabel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransparentLabelControl_TransparentLabel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WizardControl_HeaderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardControl_HeaderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WizardControl_WelcomeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardControl_WelcomeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WizardControl_Wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardControl_Wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
